### ISSUE TITLE
Spec version tags

### ISSUE THREAD

**Issue by LewisGaul** [KenKundert/nestedtext_tests#4]
Would it be possible to use tags/branches for the version of the spec the tests corresponds to? zig-nestedtext currently still doesn't support 1.3.3, which is what the master branch of this repo now corresponds to. Yes I'm using a git submodule on a fixed commit so it's not a big deal, but it would be good to have tracking of the different versions.

**Comment by erikw** [comment]
I would be in big favor of this as well!

Having a git tag in this repo matching the language version would make it a lot easier for keep nestedtext implementations up to date.

**Comment by KenKundert** [comment]
Done.

**Comment by erikw** [comment]
Thanks!
